// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjmzxndvxrxjnatcvjgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbXp4bmR2eHJ4am5hdGN2amd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTYzNTIsImV4cCI6MjA2ODU5MjM1Mn0.0a4Bfl_2z3O4uFYcN5cNytZLZ797_jJiAUUOgw7cT4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});